# Generated by Django 4.2.16 on 2024-11-29 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0002_partnershipquestion_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipanswer',
            name='answered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipanswer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partnershipquestion',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PartnershipChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='partner.partnershipquestion')),
            ],
        ),
        migrations.AddField(
            model_name='partnershipanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='partner.partnershipchoice'),
        ),
    ]
